### PR TITLE
Fixed 1_18_R1 NMS Issue

### PR DESCRIPTION
**Pull request by Craftit7**
Fixed the NMS Issue that everyone wanted fixed. Thanks to @IxeYgrek for hiring me from Fiverr and asking me to do a pull request.

### CODE REVIEW

**Comment by PIBM** [comment]
Hi! Are you still building it as per the documentation for ancillary compatibility ?

**Comment by drew6017** [comment]
Hey I took a look at your pull @Craftit7. But craftbukkit-1.18.2 thinks you missed one. What version did you build this for?

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.divisionind.bprm.nms.NBTMap.setNBT(NBTMap.java:47) ~[?:?]
        at com.divisionind.bprm.nms.NMSItemStack.setNBTOnce(NMSItemStack.java:72) ~[?:?]
        at com.divisionind.bprm.BackpackObject.getBackpack(BackpackObject.java:108) ~[?:?]
        at com.divisionind.bprm.BackpackObject.init(BackpackObject.java:61) ~[?:?]
        at com.divisionind.bprm.BackpackRecipes.<init>(BackpackRecipes.java:53) ~[?:?]
        at com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:117) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:503) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:429) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:604) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:406) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:986) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296) ~[craftbukkit-1.18.2-R0.1-SNAPSHOT.jar:3453-Bukkit-64db512]
```

**Comment by IxeYgrek** [comment]
Only tested for PaperMC 1.18.1 build 216 (latest build for 1.18.1)

**Comment by Craftit7** [comment]
I made it for 1.18.1; I'm still looking for a 1.18.2 fix

**Comment by Craftit7** [comment]
> Hi! Are you still building it as per the documentation for ancillary compatibility ?

I built it as it says in the README.md

**Comment by Craftit7** [comment]
Should I change something?

**Comment by Craftit7** [comment]
> Gradle must be run with Java 11. However, most Minecraft servers are still on Java 8, so, the final plugin must be built for Java 8.

**Comment by Craftit7** [comment]
I searched online and some sites tell me to update the java used, should I make it Java 17?

**Comment by Craftit7** [comment]
Yes I totally get the Java 8 concept
Hmm this is confusing
If you can contact me on discord so we work together, would be great. craftit7#9142

**Comment by drew6017** [comment]
Well I would, but life is kinda crazy right now and I have no time. That's why I didn't do this myself lol.

**Comment by OllieRG525** [comment]
Hi! Are you still going to add support for 1.18.2? and if so, how close is it to done?

**Comment by Craftit7** [comment]
I have some school things and I don't have enough time to research all the nms classes; If someone can provide me with a remapped list maybe? Anyways, I have a vacation after like 20 days so I can finish everything in that vacation. I'm very sad that my first vacation didn't last long enough to finish the 1.18.2 version

**Pull request merged**
